version: '3.4'

services:
  fleet-back:
    image: fleet:latest
    # image: <ID>.azurecr.io/fleet-back:latest
    container_name: tfe-fleet-back
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://<DB_SERVER_NAME>.postgres.database.azure.com:5432/<DB_NAME>?ssl=true&sslmode=require
      - SPRING_DATASOURCE_USERNAME=<DB_USER_NAME>
      - SPRING_DATASOURCE_PASSWORD=<DB_USER_PWD>   
  fleet-front:
    image: fleetfront:latest
    # image: <ID>.azurecr.io/fleet-front:latest
    container_name: tfe-fleet-front
    # build:
    #   context: .
    #   dockerfile: ../fleet-front/Dockerfile
    links:
      - "fleet-back"
    depends_on:
      - "fleet-back"
    ports:
      - "8181:8181"      